### ISSUE TITLE
SyncTrayzor 1.1.9 not talking right to syncthing 0.13.1

### ISSUE THREAD

**Issue by vr-jack** [canton7/SyncTrayzor#262]
Upgraded one computer and did a fresh install on another computer (and did syncthing 0.13.1 upgrade). The folders disappear, the device says unknown, and there is no id. Web interface for syncthing is just fine.

windows 7 Pro

The new install is actually on a brand new computer install, which is why I did the upgrades.

**Comment by canton7** [comment]
Sounds like it's Syncthing's issue, not SyncTrayzor's?

**Comment by vr-jack** [comment]
Syncthing itself works, and I can hit it's web interface to use it with firefox. The SyncTrayzor interface doesn't work (which is weird, as it looks like the web interface).

**Comment by canton7** [comment]
OK, something funky's going on. Try refreshing it? (Syncthing - Refresh Browser). Otherwise we're into debugging javascript...

**Comment by vr-jack** [comment]
Very funky. I switched over to the window on my new computer and it showed properly (before I did anything to it). The old computer is still in never never land.

**Comment by vr-jack** [comment]
FYI, After some time, my other computer also just suddenly sync'd back in and worked. It was giving an error on the Listeners while it was broke. I didn't do anything to fix it other than let it just run for awhile. Restarts, reinstalls, refresh browser all failed to do anything.

**Comment by opuslux** [comment]
Same situation here. But i still hope and wait for things getting back to normal as stated by vr-jack.

![image](https://cloud.githubusercontent.com/assets/6863949/15388396/12f03754-1db2-11e6-90af-5e2711247a1d.png)

**Comment by canton7** [comment]
I saw something similar on the forums, actually, where the web UI (it wasn't related to SyncTrayzor: it was the web UI in general) didn't work while Syncthing migrated the database to the 0.13 format.

Can you confirm that opening the web interface in a browser definitely does not exhibit this problem, at exactly the same time that SyncTrayzor does exhibit the problem?

**Comment by opuslux** [comment]
I can confirm this. And i'm happy to tell that the first machine came back to normal behaviour around 1 hour after the update. Thank you.

**Comment by canton7** [comment]
Can you edit SyncTrayzor.exe.config (which lives alongside SyncTrayzor.exe) and change `<CefRemoteDebuggingPort>0</CefRemoteDebuggingPort>` to `<CefRemoteDebuggingPort>2004</CefRemoteDebuggingPort>` (and restart SyncTrayzor).

When the issue next appears, open Chrome (i.e. normal standalone Chrome) and go to http://localhost:2004, then click on the single link that appears. Click the 'Console' tab at the top, and see what appears (there should be a bunch of errors). What are these?

Also check the 'Network' tab. You might see a bunch of failed requests. If you click one of these, you'll see details about the request. That will be useful to see.

**Comment by canton7** [comment]
Actually, another thing to try (which might be easier) is to delete `C:\Users\<You>\AppData\Local\SyncTrayzor\cef\cache`.

**Comment by opuslux** [comment]
I see a page like this:

![image](https://cloud.githubusercontent.com/assets/6863949/15388865/573fb05e-1db4-11e6-86eb-c8ae08b66de9.png)

When I click the link I arrive on a blank page. Probably the same locking problem.
Adress is then something like

http://localhost:2004/devtools/inspector.html?ws=localhost:2004/devtools/page/xxxx-xxx....

But only a white blank page is displayed.

**Comment by opuslux** [comment]
Deleting the cache solved the problem immediately. For other users using the portable Version of SyncTrayzor: The cef folder may reside in the same folder where SyncTrayzor.exe is.

**Comment by canton7** [comment]
Aah, OK, so the embedded browser (CEF) is probably caching some javascript for a while, or some such. Yay.

Annoyingly, I can't simply delete the cache on startup (for example) as it contains the local storage, which contains the user's langauge selection for Syncthing.

Having said that, it looks like there's a switch to disable the cache but keep local storage which I'd missed. I'll try that...

**Comment by canton7** [comment]
Can someone who's still seeing this problem try this build please? https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.9.354/artifacts

**Comment by opuslux** [comment]
![image](https://cloud.githubusercontent.com/assets/6863949/15390110/59211cc2-1dba-11e6-8ca4-3b7ac3117007.png)

Sorry :(

**Comment by canton7** [comment]
OK, that's something new....

Can you post your log please (my email's on my github profile page if you want to keep it private).

**Comment by opuslux** [comment]
Can you tell me which logfile exactly?

**Comment by canton7** [comment]
Go to File -> Settings -> Logging + STTRACE, click "Show SyncTrayzor log file".

**Comment by canton7** [comment]
This build should fix that: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.9.355/artifacts

**Comment by canton7** [comment]
(It didn't work, apparently)

Trying another approach. Build to follow shortly.

**Comment by canton7** [comment]
Would someone who can still reproduce this mind trying this build? Thanks! https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.9.356/artifacts

**Comment by JLJTGR** [comment]
Doesn't seem to fix the issue for me, nor did 1.1.10 that offered to update.  It doesn't bother me much, so I'll let it sit for now... and I have 3 other machines that will probably do the same when I turn them on and make them get ST0.13.1

**Comment by canton7** [comment]
Oh well. I can't reproduce the issue here, so I'm having to guess at what the problem is, then guess at potential ways to kick the embedded browser into behaving...

**Comment by mikeharding** [comment]
I had the same problem on 2 Windows PCs and was able to fix the issue by deleting the cache.

**Comment by opuslux** [comment]
The version 1.1.10 solved the problem for me. Thank you!

**Comment by JLJTGR** [comment]
Over night, my primary PC fixed itself while running 1.1.10... but it seemed like old versions would do that as well after a while.
I booted up another machine, updated it to 1.1.10 first, then updated ST to 0.13.1 and still had the previous problem.  So it really just looks like time fixes it if you don't want to go and delete things.

**Comment by canton7** [comment]
Yeah, it's looking that way.

It's annoying that I can't reproduce it. I might hack something together to go and delete the right files whenever Syncthing restarts, or I might look at what cache headers Syncthing is sending out...

**Comment by marclaporte** [comment]
I confirm issue on v0.13.2 and 1.1.10 (Shall I send you the logs?)

Thanks!

**Comment by canton7** [comment]
@opuslux:

> When I click the link I arrive on a blank page. Probably the same locking problem.

Bleh, looks like Chrome changed how their debugging tools work, and broke everything....

@marclaporte Mind downloading [this version](https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.10.362/artifacts) (when it's finished building) and following [these instructions](https://github.com/canton7/SyncTrayzor/issues/262#issuecomment-220271295)?

I'm interested in screenshots of the 'Console' and 'Network' panels as you click Syncthing -> Refresh Browser in SyncTrayzor.

Thanks!

**Comment by canton7** [comment]
What timezone is everyone in?

Tracking this issue down in the Syncthing sources, and it looks like it might be timezone-related....

**Comment by opuslux** [comment]
Hello from Switzerland

**Comment by canton7** [comment]
So GMT+1? Hmm, that messes up my nice little theory...

**Comment by opuslux** [comment]
In wintertime it is GMT+1 but right now in summtertime it is GMT+2. I hope this is good news ;)

**Comment by canton7** [comment]
Nah, it's the wrong way: I need you to be behind GMT for my theory to work...

**Comment by marclaporte** [comment]
EDT, which is UTC -4

**Comment by CaiB** [comment]
I can confirm, that on two computers (Win 10 x64, ST 0.13.2), it was not showing up properly, as stated in this issue. I was able to click "Syncthing->Open in external browser", to open the interface in Edge which worked perfectly. Deleting the cef cache folder fixed the problem on both computers.

**Comment by canton7** [comment]
I'm almost certain it's a Syncthing caching issue now, although I can't put my finger on what's causing it (as I can't replicate it).

**Comment by marclaporte** [comment]
Problem went away on my end... (so yup, looks like cache)

**Comment by DHowett** [comment]
Agreed. Would it be reasonable to wipe the cache for each SyncTrayzor (or even just syncthing) update?

**Comment by canton7** [comment]
Wiping it on SyncTrayzor updates won't make any difference, since that's unrelated to Syncthing upgrades. Actually wiping the cache is also a bit of a problem: the embedded browser doesn't provide a means of doing this.

I'm currently [working out a better caching strategy with Syncthing](https://github.com/syncthing/syncthing/issues/3182), which should (in theory, if our guess at what's causing it is right) sort it out.

**Comment by canton7** [comment]
Right, I've landed https://github.com/syncthing/syncthing/pull/3221, and the next version will do a complete cache refresh when you click Syncthing -> Refresh Browser (or hit F5). That should take care of everything...

**Comment by norgeous** [comment]
@canton7 thanks for SyncTrayzor love the app!
I just ran into this bug when going from v0.13.4 to v0.13.5.
I could not see any of my recent GUI changes, and had to delete `C:\Users\norgeous\AppData\Local\SyncTrayzor\cef`
Please make a release soon!

**Comment by canton7** [comment]
That release has been made, and the Syncthing patches landed. Closing.

**Comment by opuslux** [comment]
Sorry to come back on this but I'm facing the same issue on my intel compute stick (32bit) when there is no screen physically attached. Version is 14.6. While I can connect to Syncthing through chrome SyncTrayzor stays with a white window.

But: I remembered having some similar issues when my laptop had a closed lid and i was accessing it via remote access. Same here: Monitor attached: Works. No monitor: White SyncTrayzor.

**Comment by canton7** [comment]
Open a new issue please, your issue is different. Tried disabling hardware rendering in SyncTrayzor's settings?
